### ISSUE TITLE
Way to change background color when entering different area of page

### ISSUE THREAD

**Issue by zeckdude** [ehsan-shv/react-nice-scroll#2]
Thanks for all the awesome work on this package! Is there a way to change the background gradient color to change whenever you enter a new area on the page as you scroll down?

**Comment by ehsan-shv** [comment]
Thank! This library uses GSAP and you can easily change the background color by GSAP. [Read more](https://greensock.com/forums/topic/25648-change-backgroundcolor-on-scroll/).

**Comment by zeckdude** [comment]
Hmm that looks interesting and the code sample in the post you linked to looks easy enough, so thanks for sharing. I'm still struggling how their API would work together with yours though. I'm specifically looking at using your image sequence animation so if you would be able to give me some basic code to get that started to work with GSAP to change the background color, that would really be amazing!
